services:
  - type: web
    name: passport-scanner-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    plan: free
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: TESSDATA_PREFIX
        value: /home/.tessdata
